import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();

const sources = [
  'tokens/Border/Mode 1.json',

  'tokens/Colour / Primitive/Mode 1.json',
  'tokens/Colour / Semantic/Light.json',

  'tokens/Layout/Mode 1.json',
  'tokens/Spacing/Mode 1.json',

  'tokens/Type / Primitive/Mode 1.json',
  'tokens/Type / Semantic/Desktop.json',

  'tokens/Units/Mode 1.json',
];
 
const outputFile = path.join(root, 'src/styles/tokens.css');

const tokens = new Map();

function toKebab(input) {
  return String(input)
    .replace(/\$/g, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/(\d)([A-Z]+)/g, '$1-$2')
    .replace(/[\s_.\/]+/g, '-')
    .replace(/[^a-zA-Z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function tokenName(parts) {
  return parts.map(toKebab).filter(Boolean).join('-');
}

function referenceToCss(value) {
  return value.replace(/\{([^}]+)\}/g, (_, reference) => {
    const refName = tokenName(reference.split('.'));
    return `var(--${refName})`;
  });
}

function shouldUsePx(sourcePath, name, type) {
  const lowerPath = sourcePath.toLowerCase();
  const lowerName = name.toLowerCase();

  if (type === 'dimension') return true;

  if (
    lowerPath.includes('/spacing/') ||
    lowerPath.includes('/border/') ||
    lowerPath.includes('/layout/') ||
    lowerPath.includes('/units/')
  ) {
    return true;
  }

  if (
    lowerName.includes('font-size') ||
    lowerName.includes('letter-spacing') ||
    lowerName.includes('line-height')
  ) {
    return true;
  }

  return false;
}

function valueToCss(value, sourcePath, name, type) {
  if (value && typeof value === 'object' && '$value' in value) {
    return valueToCss(value.$value, sourcePath, name, value.$type ?? type);
  }

  if (typeof value === 'string') {
    return referenceToCss(value);
  }

  if (typeof value === 'number') {
    return shouldUsePx(sourcePath, name, type) ? `${value}px` : String(value);
  }

  if (typeof value === 'boolean') {
    return String(value);
  }

  return String(value);
}

function addToken(parts, rawValue, sourcePath, type) {
  const name = tokenName(parts);
  const value = valueToCss(rawValue, sourcePath, name, type);

  if (tokens.has(name)) {
    console.warn(`Duplicate token overwritten: --${name}`);
  }

  tokens.set(name, value);
}

function walk(node, sourcePath, parts = [], inheritedType) {
  if (!node || typeof node !== 'object') return;

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;

    const nextParts = [...parts, key];

    if (value && typeof value === 'object' && '$value' in value) {
      const type = value.$type ?? inheritedType;
      const rawValue = value.$value;

      if (
        rawValue &&
        typeof rawValue === 'object' &&
        !Array.isArray(rawValue)
      ) {
        for (const [subKey, subValue] of Object.entries(rawValue)) {
          addToken([...nextParts, subKey], subValue, sourcePath, type);
        }
      } else {
        addToken(nextParts, rawValue, sourcePath, type);
      }
    } else {
      walk(value, sourcePath, nextParts, value?.$type ?? inheritedType);
    }
  }
}

for (const source of sources) {
  const fullPath = path.join(root, source);

  if (!fs.existsSync(fullPath)) {
    console.warn(`Skipped missing file: ${source}`);
    continue;
  }

  const json = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
  walk(json, source);
}

const css = `/**
 * Generated by scripts/build-tokens.mjs
 * Do not edit manually.
 */

:root {
${[...tokens.entries()]
  .map(([name, value]) => `  --${name}: ${value};`)
  .join('\n')}
}
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, css);

console.log(`Generated ${tokens.size} tokens at src/styles/tokens.css`);